#ifndef DEFINE_H
#define DEFINE_H

#define BLOCK_SIZE 512
#define DIRECTORY_BEGIN 240
#define DIRECTORY_NUM_BLOCKS 14
#define FAT_BACKUP_BEGIN 239
#define FAT_MAIN_BEGIN 254
#define FILE_ENTRY_SIZE 32
#define MAX_FAT_ENTRIES 256
#define MAX_FILE_ENTRIES 224
#define MAX_ENCODED_FILENAME_LENGTH 11
#define MAX_READABLE_FILENAME_LENGTH 13
#define SIGNATURE "?MEMEFS++CMSC421"
#define SUPERBLOCK_BACKUP_BEGIN 0
#define SUPERBLOCK_MAIN_BEGIN 255
#define USER_DATA_BEGIN 19
#define USER_DATA_NUM_BLOCKS 220
#define FUSE_USE_VERSION 35
#include <fuse3/fuse.h>

#endif // DEFINE_H